package channel

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptrace"
	"regexp"
	"strings"
	"sync"
	"syscall"
	"time"

	common2 "github.com/lza6/new-api-Max/common"
	"github.com/lza6/new-api-Max/logger"
	"github.com/lza6/new-api-Max/relay/common"
	"github.com/lza6/new-api-Max/relay/constant"
	"github.com/lza6/new-api-Max/relay/helper"
	"github.com/lza6/new-api-Max/relaykit/types"
	"github.com/lza6/new-api-Max/service"
	"github.com/lza6/new-api-Max/setting/operation_setting"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

// ApplyUpstreamBodyMetadata restores metadata that net/http cannot infer from
// a ReplayableBody. Callers must pass the original body because NewRequest
// hides its dynamic type behind req.Body's io.ReadCloser wrapper.
func ApplyUpstreamBodyMetadata(req *http.Request, body io.Reader) {
	replayable, ok := body.(common2.ReplayableBody)
	if !ok {
		return
	}

	// BodyStorage structurally satisfies ReplayableBody, but it also exposes
	// io.Closer. If a caller passes the storage directly instead of using
	// NewReplayableBodyReader, hide Close before the transport takes ownership
	// of req.Body so the shared replay source remains available to GetBody.
	if _, rawStorage := body.(common2.BodyStorage); rawStorage {
		req.Body = io.NopCloser(body)
	}

	req.ContentLength = replayable.Size()
	if req.GetBody == nil {
		req.GetBody = replayable.NewReader
	}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	// T5: 网关 request-id 全链路透传——中继把网关生成的 request-id 带给上游，
	// 便于上游回包/日志关联；显式 Header Override 在 SetupRequestHeader 之后应用，
	// 仍可覆盖此默认值（现有 applyHeaderOverrideToRequest 后置）。
	if operation_setting.IsRequestIdForwardingEnabled() {
		if requestID := c.GetString(common2.RequestIdKey); requestID != "" {
			req.Set(common2.RequestIdKey, requestID)
		}
	}
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

// bodySize 返回可回放请求体的字节数；不可回放时返回 0。
func bodySize(body io.Reader) int64 {
	if r, ok := body.(common2.ReplayableBody); ok {
		return r.Size()
	}
	return 0
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	// [修复防御] 出站请求体压缩（渠道 opt-in）：大 JSON 请求体 gzip 后上传，
	// 缩短 5Mbps 上行下的首字延迟（frt 与 request_bytes 单调正相关）。
	// 返回 compressed=true 时必须在本次请求结束前 Close 存储，并设置
	// Content-Encoding: gzip。fail-open：任何异常都退回明文，绝不拒绝请求。
	originalSize := bodySize(requestBody)
	requestBody, compressed, compressionCloser := common.MaybeCompressOutboundBody(c, info, requestBody)
	if compressionCloser != nil {
		defer compressionCloser.Close()
	}
	if info != nil && info.RequestId != "" {
		// 实时请求详情：记录请求体压缩前后字节（未压缩时 compressedBytes=originalSize）。
		compressedSize := originalSize
		if compressed {
			compressedSize = bodySize(requestBody)
		}
		service.LiveSetCompression(info.RequestId, originalSize, compressedSize, compressed)
	}
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	// [修复防御] 压缩后必须标记 Content-Encoding，且置于 header override 之后：
	// 编码必须与实际 body 一致，不能被 override 改写成错误值导致上游解析失败。
	if compressed {
		req.Header.Set("Content-Encoding", "gzip")
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	targetConn, _, err := websocket.DefaultDialer.Dial(fullRequestURL, targetHeader)
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", common.SanitizeURLForLog(fullRequestURL), err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func startPingKeepAlive(c *gin.Context, pingInterval time.Duration) (context.CancelFunc, <-chan struct{}) {
	pingerCtx, stopPinger := context.WithCancel(context.Background())
	done := make(chan struct{})

	gopool.Go(func() {
		defer close(done)
		defer func() {
			// 增加panic恢复处理
			if r := recover(); r != nil {
				logger.LogDebug(c, "SSE ping goroutine panic recovered: %v", r)
			}
			logger.LogDebug(c, "SSE ping goroutine stopped")
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			logger.LogDebug(c, "SSE ping ticker stopped")
		}()

		var pingMutex sync.Mutex
		logger.LogDebug(c, "SSE ping goroutine started")

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					logger.LogDebug(c, "SSE ping error, stopping goroutine: %s", err.Error())
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				logger.LogDebug(c, "SSE ping goroutine timeout, stopping")
				return
			}
		}
	})

	return stopPinger, done
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	mutex.Lock()
	defer mutex.Unlock()

	// Bound the write so a slow client cannot block this goroutine forever;
	// doRequest's defer waits for the pinger to exit before returning.
	helper.ExtendWriteDeadline(c)
	err := helper.PingData(c)
	if err != nil {
		logger.LogError(c, "SSE ping error: "+err.Error())
		return err
	}

	logger.LogDebug(c, "SSE ping data sent")
	return nil
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}

// keepUpstreamRedirectResponse stops net/http from following redirects while
// returning the upstream 3xx response to the relay without an extra error.
func keepUpstreamRedirectResponse(_ *http.Request, _ []*http.Request) error {
	return http.ErrUseLastResponse
}

// isRequestTimeout 判断上游请求是否因超时失败（http.Client.Timeout / context
// deadline / net.Error.Timeout）。超时应映射为 504 Gateway Timeout，而不是笼统 500。
func isRequestTimeout(err error) bool {
	if errors.Is(err, context.DeadlineExceeded) {
		return true
	}
	var ne net.Error
	return errors.As(err, &ne) && ne.Timeout()
}

// resolveRelayTimeout 解析渠道级整请求超时覆盖（透传语义）：
// override == nil → 沿用全局 globalSeconds（不覆盖）；
// override < 0 → 非法值，回退全局；
// override == 0 → 显式关闭整请求超时（交给上游决定，真正的透传）；
// override > 0 → 渠道自定义超时秒数。
// isUpstreamUnreachable 判断错误是否为「网关到上游的网络层失败」—— 请求从未
// 到达上游应用，因此上游侧无任何记录。覆盖三类：
//  1. 连接被拒（connection refused）/ 网络不可达（no route to host）
//  2. TLS 或连接中途断开（EOF / unexpected EOF / connection reset）
//  3. DNS 解析失败（no such host）
//
// 注意：超时（Timeout）不算「不可达」，由 isRequestTimeout 单独映射 504。
func isUpstreamUnreachable(err error) bool {
	if err == nil {
		return false
	}
	// 超时优先由 504 分支处理，不在这里重复归类。
	if isRequestTimeout(err) {
		return false
	}
	var dnsErr *net.DNSError
	if errors.As(err, &dnsErr) {
		return true
	}
	var opErr *net.OpError
	if errors.As(err, &opErr) {
		return true
	}
	if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) ||
		errors.Is(err, syscall.ECONNREFUSED) || errors.Is(err, syscall.ECONNRESET) ||
		errors.Is(err, syscall.EHOSTUNREACH) || errors.Is(err, syscall.ENETUNREACH) {
		return true
	}
	// 兜底：Go 的 http 包在连接中途断开时常返回未包装的字符串错误，
	// 无法用 errors.Is 匹配，退化为关键字判定（仅在网络层分支使用，不影响业务错误）。
	msg := strings.ToLower(err.Error())
	for _, marker := range []string{
		"connection refused", "no route to host", "network is unreachable",
		"unexpected eof", "connection reset", "broken pipe",
		"no such host", "tls handshake timeout", "remote end closed connection",
	} {
		if strings.Contains(msg, marker) {
			return true
		}
	}
	return false
}

// summarizeNetworkError 把底层网络错误压成一句人话，供客户端直接展示
// （避免把 Go 的完整 URL/Dial 细节透给终端用户，同时保留可诊断信息）。
func summarizeNetworkError(err error) string {
	msg := strings.ToLower(err.Error())
	switch {
	case strings.Contains(msg, "connection refused"):
		return "connection refused"
	case strings.Contains(msg, "no route to host"):
		return "no route to host"
	case strings.Contains(msg, "no such host"):
		return "dns resolution failed"
	case strings.Contains(msg, "unexpected eof"), strings.Contains(msg, "remote end closed connection"):
		return "connection closed by upstream"
	case strings.Contains(msg, "connection reset"), strings.Contains(msg, "broken pipe"):
		return "connection reset by upstream"
	default:
		return "network error to upstream"
	}
}

func resolveRelayTimeout(globalSeconds int, override *int) (seconds int, overridden bool) {
	if override == nil || *override < 0 {
		return globalSeconds, false
	}
	return *override, true
}

// withUpstreamTimingTrace 注入 httptrace 钩子，采集三段耗时（相对发起时刻）：
// 建连（ConnectStart→ConnectDone，含 TLS）、请求体写完（WroteRequest）、
// 上游响应头到达（GotFirstResponseByte）。全部采集完后一次性回调
// info.OnUpstreamTiming，供实时面板展示「上传 vs 上游首 token」的拆分。
//
// 采用 mutex 保护共享时间点（钩子可能在不同 goroutine 触发）。仅在
// info.OnUpstreamTiming 非 nil 时由调用方启用，未启用则零开销。
func withUpstreamTimingTrace(ctx context.Context, info *common.RelayInfo, c *gin.Context) context.Context {
	start := time.Now()
	var mu sync.Mutex
	var connectDone, wroteDone, firstByte time.Time
	toMs := func(t time.Time) int64 {
		if t.IsZero() {
			return -1
		}
		return t.Sub(start).Milliseconds()
	}
	emit := func() {
		connectMs := toMs(connectDone)
		uploadMs := toMs(wroteDone)
		ttfbMs := toMs(firstByte)
		info.UpstreamConnectMs = connectMs
		info.UpstreamUploadMs = uploadMs
		info.UpstreamTtfbMs = ttfbMs
		if info.OnUpstreamTiming != nil {
			info.OnUpstreamTiming(connectMs, uploadMs, ttfbMs)
		}
	}
	trace := &httptrace.ClientTrace{
		ConnectDone: func(_, _ string, _ error) {
			mu.Lock()
			connectDone = time.Now()
			mu.Unlock()
		},
		WroteRequest: func(_ httptrace.WroteRequestInfo) {
			mu.Lock()
			wroteDone = time.Now()
			mu.Unlock()
		},
		GotFirstResponseByte: func() {
			mu.Lock()
			firstByte = time.Now()
			mu.Unlock()
			emit()
		},
	}
	return httptrace.WithClientTrace(ctx, trace)
}

func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	// B1-2 SSRF 二次解析：在即将发起上游请求时再次校验目标地址（防 DNS
	// rebinding「保存合法、使用时解析到内网」窗口）。结果按 host 缓存 5 分钟。
	// 拒绝不 skip retry：换渠道后 base_url 不同，可正常继续。
	if req != nil && req.URL != nil {
		if err := service.ValidateChannelURL(req.URL.String()); err != nil {
			logger.LogError(c, "ssrf guard: "+err.Error())
			return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream address rejected"))
		}
	}
	client, err := service.GetHttpClientWithProxySettings(info.ChannelSetting.Proxy, info.ChannelSetting)
	if err != nil {
		return nil, fmt.Errorf("new proxy http client failed: %w", err)
	}
	// Clients are cached and shared across channels, so override redirect
	// behavior on a shallow copy instead of mutating the cached client. This
	// still reuses its transport and connection pools, including HTTP/2's
	// transparent stream retries.
	relayClient := *client
	relayClient.CheckRedirect = keepUpstreamRedirectResponse
	// [修复防御] 渠道级整请求超时覆盖（透传语义）：上游慢但正常的长请求
	// （如 /v1/responses 非流/流式长输出）不再被全局 RELAY_TIMEOUT 到点 kill
	// 成 504 —— 由渠道设置 relay_timeout_seconds 决定（0=不设超时）。
	if seconds, overridden := resolveRelayTimeout(common2.RelayTimeout, info.ChannelSetting.RelayTimeoutSeconds); overridden {
		if seconds > 0 {
			relayClient.Timeout = time.Duration(seconds) * time.Second
		} else {
			relayClient.Timeout = 0
		}
		logger.LogInfo(c, fmt.Sprintf("channel relay timeout override: %ds", seconds))
	}
	if common2.DebugEnabled && req != nil && req.URL != nil {
		policy := service.NormalizeHTTPTransportPolicy(info.ChannelSetting)
		logger.LogDebug(c, fmt.Sprintf(
			"http transport select: host=%s protocol=%s shards=%d policy=%s",
			req.URL.Host,
			policy.Protocol,
			policy.Shards,
			policy.String(),
		))
	}

	var stopPinger context.CancelFunc
	var pingerDone <-chan struct{}
	if info.IsStream {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			stopPinger, pingerDone = startPingKeepAlive(c, pingInterval)
			// 使用defer确保在任何情况下都能停止ping goroutine
			defer func() {
				if stopPinger != nil {
					stopPinger()
					<-pingerDone
					logger.LogDebug(c, "SSE ping goroutine stopped by defer")
				}
			}()
		}
	}

	// 延迟拆解：用 httptrace 采集「建连/上传/首字节」三段耗时，供实时面板区分
	// 「网关→上游上传」与「上游首 token」。仅在有回调时启用（零开销路径）。
	if info != nil && info.OnUpstreamTiming != nil {
		req = req.WithContext(withUpstreamTimingTrace(req.Context(), info, c))
	}

	resp, err := relayClient.Do(req)
	if err != nil {
		logger.LogError(c, "do request failed: "+err.Error())
		if isRequestTimeout(err) {
			// 上游总超时（如 RELAY_TIMEOUT）：映射 504，语义准确、可观测可辨。
			return nil, types.NewErrorWithStatusCode(err, types.ErrorCodeDoRequestFailed, http.StatusGatewayTimeout,
				types.ErrOptionWithHideErrMsg("upstream request timed out"))
		}
		if isUpstreamUnreachable(err) {
			// [修复防御] 网络层失败（连接被拒 / TLS 中断 unexpected EOF / DNS 失败）
			// 请求根本没到达上游应用，上游侧不会有记录——此前统一报 500 会让用户
			// 误判为「网关内部故障」，监控也无法与真实 500 分离。
			// 映射 502 Bad Gateway + upstream_unreachable 错误码，语义准确；
			// status>=500 仍命中 ErrClassServerError → 渠道冷却与重试语义不变。
			logger.LogWarn(c, "upstream unreachable (network layer, request never reached upstream): "+err.Error())
			return nil, types.NewErrorWithStatusCode(err, types.ErrorCodeUpstreamUnreachable, http.StatusBadGateway,
				types.ErrOptionWithHideErrMsg("upstream unreachable: "+summarizeNetworkError(err)))
		}
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream error: do request failed"))
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}
	if common2.DebugEnabled {
		policy := service.NormalizeHTTPTransportPolicy(info.ChannelSetting)
		logger.LogDebug(c, fmt.Sprintf(
			"http transport negotiated: host=%s protocol=%s shards=%d policy=%s negotiated=%s",
			req.URL.Host,
			policy.Protocol,
			policy.Shards,
			policy.String(),
			resp.Proto,
		))
	}

	if upID := resp.Header.Get(common2.RequestIdKey); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := newTaskAPIRequest(c, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	// Do NOT wrap requestBody in a GetBody closure here: returning the same
	// (already consumed) reader would make any transport-level retry silently
	// replay an empty body. http.NewRequest already derives a correct,
	// snapshot-based GetBody for *bytes.Reader/Buffer/strings.Reader bodies
	// (which most task adaptors pass in); ApplyUpstreamBodyMetadata wires the
	// same contract for bodies that explicitly implement ReplayableBody.
	// Otherwise GetBody stays nil so the transport fails the retry instead of
	// sending a corrupted request.

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// T5: 任务提交通道统一透传网关 request-id（受同一开关控制），
	// 使任务提交的上游请求与发起请求可贯穿关联。
	if operation_setting.IsRequestIdForwardingEnabled() {
		if requestID := c.GetString(common2.RequestIdKey); requestID != "" {
			req.Header.Set(common2.RequestIdKey, requestID)
		}
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func newTaskAPIRequest(c *gin.Context, fullRequestURL string, requestBody io.Reader) (*http.Request, error) {
	if c == nil || c.Request == nil {
		return nil, errors.New("task client request is missing")
	}
	return http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
}
